# permissions for end users to view hubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hub-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: node-operator
    app.kubernetes.io/part-of: node-operator
    app.kubernetes.io/managed-by: kustomize
  name: hub-viewer-role
rules:
- apiGroups:
  - node.rss3.io
  resources:
  - hubs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.rss3.io
  resources:
  - hubs/status
  verbs:
  - get
