apiVersion: node.rss3.io/v1alpha1
kind: Indexer
metadata:
  labels:
    app.kubernetes.io/name: indexer
    app.kubernetes.io/instance: indexer-sample
    app.kubernetes.io/part-of: node-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: node-operator
  name: indexer-sample
spec:
  network: crossbell
  worker: crossbell
  endpoint: https://rpc.crossbell.io
  # TODO(user): Add fields here
  database:
    driver: cockroachdb
    partition: true
    uri:
      secretKeyRef:
        name: cockroachdb
        key: uri
