apiVersion: node.rss3.io/v1alpha1
kind: Hub
metadata:
  labels:
    app.kubernetes.io/name: hub
    app.kubernetes.io/instance: hub-sample
    app.kubernetes.io/part-of: node-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: node-operator
  name: hub-sample
spec:
  # TODO(user): Add fields here
