name: Build and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - deploy/**
      - config/**
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/node-operator
      context: .
      dockerfile: ./Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy-dev:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/node-operator
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: network
      releaseName: rss3-node-operator
      revision: main
      dir: deploy/dev
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
#  deploy-prod:
#    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
#    needs:
#      - build
#      - deploy-dev
#    with:
#      images: rss3/node-operator
#      tag: sha-${{ github.sha }}
#      cluster: prod
#      namespace: network
#      releaseName: rss3-node-operator
#      revision: main
#      dir: deploy/prod
#    secrets:
#      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
